# 389. Find the Difference

# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one 
# more letter at a random position.

# Find the letter that was added in t.

# Example:

# Input:
# s = "abcd"
# t = "abcde"

# Output:
# e

# Explanation:
# 'e' is the letter that was added.

class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        dicts, dictt = {}, {}
        for i in s:
            dicts[i] = dicts[i] + 1 if i in dicts else  1
        print(dicts)
        for i in t:
            dictt[i] = dictt[i] + 1 if i in dictt else  1
        print(dictt)
        for keys in dictt:
            print(keys)
            if (keys not in dicts) or dictt[keys] > dicts[keys]:
                return keys
        return None